### ISSUE TITLE
Add a "View details" to error messages (or something like it) that allows a more in-depth debugging

### ISSUE THREAD

**Issue by megoth** [inrupt/generator-solid-react#119]
Most of the times this information are to be found in the console of the developer toolbar, but this might be an easier stepping stone for new developers.

Also, if it's server errors we could provide more info (even in RDF) that can be consumed and presented (maybe even in a visualized manner) in that detailed view.

I haven't written any specifics on how the detailed view should look, but it could be a modal or another type of overlay that pops into the view.

**Comment by james-martin-jd** [comment]
This was addressed in the recent 0.6.0 RC release - we have added a Learn More link to common errors in our new feature, and have begun using dokieli documentation (hosted on a new common pod) to document resolutions to more common but difficult errors.
