### ISSUE TITLE
profile picture not compatible with data browser?

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/generator-solid-react#120]
I edited my profile picture using https://dev-generator.inrupt.com/welcome# but it is not showing up on https://michielbdejong.inrupt.net/profile/card#me?

It seems to be using http://xmlns.com/foaf/0.1/img, I'm trying to see what the databrowser uses, but can't really tell from https://github.com/solid/solid-panes/blob/master/profile/profilePane.js

**Comment by michielbdejong** [comment]
It seems that the databrowser uses http://www.w3.org/2006/vcard/ns#hasPhoto instead of http://xmlns.com/foaf/0.1/img.

**Comment by james-martin-jd** [comment]
This issue was resolved in the recent 0.5.1 release. The predicates have been synchronized.
