### ISSUE TITLE
https://develop.generator.inrupt.com/welcome hangs if logged in with pod that is down

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/generator-solid-react#196]
* log in with your local https://localhost:8443/profile/card#me pod server, or some server you can stop
* stop the server
* load https://develop.generator.inrupt.com/welcome 
* it hangs, showing the cubes-spinner.

**Comment by michielbdejong** [comment]
<img width="1204" alt="Screenshot 2019-07-24 15 54 44" src="https://user-images.githubusercontent.com/408412/61799407-5d151400-ae2b-11e9-98a5-accb717725ed.png">

**Comment by james-martin-jd** [comment]
Duplicate of https://github.com/inrupt/solid-react-components/issues/30, and most likely an issue in the component library
