### ISSUE TITLE
The docs should not recommend admin privileges

### ISSUE THREAD

**Issue by Vinnl** [inrupt/generator-solid-react#237]
As @pmcb55 mentioned on a call, the README currently recommends running commands with root access. I'm presuming here that the generator itself doesn't need this, but that it's a workaround for failed `npm install -g`'s. If so, it's probably better to just point people to this page: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

(If there _is_ a good reason to run commands with root privileges, it might be good to list those reasons next to the instructions.)

**Comment by james-martin-jd** [comment]
The wording and instructions for installing npm have been updated (in develop branch aka default branch, will be in master next release). The readme isn't visible to people who npm install as far as I know, so it should only be consumed by forking or looking at the repo readme. 

The section on admin privileges has been entirely removed, and instead we link to and recommend nvm as the way to install npm. We also added a section specifically addressing the EACCES error you can get without admin privilege, linking to the doc.npmjs.org link above.
