### ISSUE TITLE
When the generator does not have permissions to set its inbox's ACL, it won't retry after it _does_ get those permissions

### ISSUE THREAD

**Issue by Vinnl** [inrupt/generator-solid-react#238]
I signed in to the generator using my account and the default permissions, which did not include Control permissions. This led to the inbox for tictactoe to be created without receiving the proper (public append) ACL configuration.

I then changed the app's permissions to include Control. However, since the inbox for tictactoe had already been created in my Pod, it did not try to set up the correct ACL any more. Hence, notifications did not work.

**Comment by james-martin-jd** [comment]
Currently our checks are happening in the incorrect order, and the ACL check is happening later in the process. We can adjust the ordering of these checks to make this possible

**Comment by james-martin-jd** [comment]
This was fixed in the 0.7.0 release
