### ISSUE TITLE
Issue at app creation

### ISSUE THREAD

**Issue by NSeydoux** [inrupt/generator-solid-react#242]
I am not an experienced JS/React developer at all, so this might just be me missing the point completely, but I keep running into an error when creating an app with the generator: 
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for test-export@^1.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@inrupt/solid-react-components'
npm ERR! notarget 
```

The app seems to be generated successfully, but when the generator tries to install it, this issue is thrown, as well as when I run `npm install` in the generated directory. If I remove the  `@inrupt/solid-react-components` dependency, the installation goes fine, but obviously there are missing packages when running `npm start`. 

If this is of any help, I'm using npm 6.10.3, and node v12.10.0, that I manage through nvm 0.34.0.

**Comment by james-martin-jd** [comment]
Thanks for reporting this. I checked in our package-lock and package.json files and I don't see that package (test-export) in either repo. Good call with the node versions, I've tested with both node v11.0.0 and v8, and for this issue report I installed v12.10.0. Im also running npm 6.10.3. 

In all 3 cases, I was unable to reproduce the issue.

Can you please tell me the steps you used to install the SDK, and which versions you installed?

**Comment by NSeydoux** [comment]
Thanks to an offline discussion, the problem was cornered to my own setup, with a .npmrc that created a conflict. The issue is now solved.
