### ISSUE TITLE
white space in notification div not clickable

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/generator-solid-react#254]
When you get a notification like 'Alice invited you to play Tic Tac Toe', you can't click on the whitespace, you have to click on the actual text. That was a confusing UX for me, is that by design or a bug?

Also mentioned this in my screencast here: 
https://www.dropbox.com/s/ybw088ac8e9odmq/Screen%20Recording%202019-10-28%20at%2012.09.15.mov?dl=0

Not sure if I had to report this in the generator or in the components or in the style guide, sorry :)

**Comment by james-martin-jd** [comment]
Currently this is a design choice, and not a bug, to prevent weird click-errors when trying to click something like delete or mark-as-read, by giving each element a distinct click event instead of a blanket event for the whole notification pane. 

We will take the feedback under advisement.

**Comment by michielbdejong** [comment]
Hm, but if someone clicks on the rectangle of one specific notification, that should count as a click, right? What if the notification has empty text? Then it wouldn't be clickable?

**Comment by james-martin-jd** [comment]
According to the [core notification shape](https://shexshapes.inrupt.net/public/notifications/core-notification.shex) we're using, the text field (as:summary) is a required field. I suppose we could have more constraints on there, such as a min-length, but the intention is all app-facing notifications must have text, so it should be a moot point.

**Comment by michielbdejong** [comment]
OK! As I said in 0:50 in https://www.dropbox.com/s/ybw088ac8e9odmq/Screen%20Recording%202019-10-28%20at%2012.09.15.mov?dl=0 it surprised me a bit that you cannot click on the white, but if that's by design then I'll close this issue.
