### ISSUE TITLE
Don't use ldp:contains inside user data

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/generator-solid-react#259]
The data browser gets totally confused when you open e.g. https://tic-tac-joe.inrupt.net/public/games/tictactoe/data.ttl (log in with tic-tac-joe / 123) because it will try to display the folder contents, and say tic-tac-joe does not have access to it.

You could say this is a databrowser issue but I think in this case the databrowser could rightly say apps should not put `ldp:contains` inside regular documents.

@megoth what do you think?

![Screenshot 2019-11-01 15 53 54](https://user-images.githubusercontent.com/408412/68033414-ea37f680-fcbf-11e9-9080-56c7d0d76f2f.png)

**Comment by james-martin-jd** [comment]
The intention there is to link to the other pod's game data, is there a better predicate to use?

**Comment by michielbdejong** [comment]
Yes, in each `{timestamp}.ttl` files you should probably add a triple that indicates the RDF type, so:
`<> a <http://data.totl.net/game/Game>`

And then in `data.ttl` (which you should probably rename to `other.ttl` or `remote.ttl`, since it links to all games that are not in the user's own TicTacToe container but elsewhere), you could just add:
`<https://tic-tac-moe.inrupt.net/public/games/tictactoe/1572260970777.ttl> a <http://data.totl.net/game/Game>`

That's a way of stating that that object exists. You could also be more explicit and say that the current user is the opponent in that game:

`<https://tic-tac-moe.inrupt.net/public/games/tictactoe/1572260970777.ttl> <https://schema.org/opponent> <https://tic-tac-moe.inrupt.net/profile/card#me>`

What you're asking for is a predicate that would state that while switching `s` and `o`. I can't think of a good one that does that, and also since you already use `<https://schema.org/opponent>`, IMHO it would complicate things to use one that means the same but in the opposite direction, but you are the first developers of a TicTacToe game, so up to you! :) Whatever you choose, I'm documenting it (merging this with the choices @pheyvaer made in https://github.com/pheyvaer/solid-chess)

**Comment by pheyvaer** [comment]
Is this also not related to the type index?

**Comment by michielbdejong** [comment]
Not directly because you want to have a list of games that you are involved in but that you do not host.

In Solid-chess each player hosts their own moves.
In Tic-Tac-Toe the initiator hosts all moves in a single document, to which the opponent gets write access.

**Comment by pheyvaer** [comment]
But I guess you can also have a type index for `<http://data.totl.net/game/Game>` that contains `<https://tic-tac-moe.inrupt.net/public/games/tictactoe/1572260970777.ttl> a <http://data.totl.net/game/Game>`, no?

**Comment by michielbdejong** [comment]
hm i think the public type index is meant to list files that you own, not just files you are interested in. but i could be wrong. in any case, i think the important step is to change the predicate used, and then a possible additional step could be to also change where the triple is stored.

**Comment by james-martin-jd** [comment]
This was updated to use `schema:hasPart` instead of `ldp:contains` in the 0.7.0 release. Old games will still be linked, but you should be able to delete them (or the entire data.ttl file, it should be automatically recreated next time you load the app).
