### ISSUE TITLE
TextEditor route not exposed

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/generator-solid-react#262]
As discussed with @james-martin-jd, there were some issues with the TextEditor example app so the route is not exposed yet in the develop branch. Created this issue to track the work to get the TextEditor pane working and re-enabled.

**Comment by michielbdejong** [comment]
@james-martin-jd which commit was it where you disabled the TextEditor route? I can't find it in https://github.com/inrupt/generator-solid-react/commits/develop

**Comment by michielbdejong** [comment]
As discussed on Slack, it probably starts working if you downgrade tripledoc from 2.1.0 to 1.4.0.

**Comment by james-martin-jd** [comment]
This has been resolved and published to the develop branch and environment, as a result I am closing this ticket.
