### ISSUE TITLE
Can Tic-Tac-Toe players edit the game doc freely?

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/generator-solid-react#263]
A finished game will have the moves that were made in a concatenated string that is the object of a `game:move` triple:
```turtle
@prefix : <#>.
@prefix g: <http://data.totl.net/game/>.
@prefix terms: <http://purl.org/dc/terms/>.
@prefix schem: <https://schema.org/>.
@prefix c: <https://tic-tac-moe.inrupt.net/profile/card#>.
@prefix n0: <https://www.w3.org/ns/activitystreams#>.
@prefix c0: </profile/card#>.

<>
    g:initialState "X";
    g:move "4-2-1-7-0-8-6-5";
    g:status "Finished";
    terms:created "2019-11-01T15:39:04+01:00";
    schem:opponent c:me;
    n0:actor c0:me.
```

Each move involves overwriting that triple with a PATCH request, for instance playing top-right after a center-opening would update the game state from '4' to '4-2', so the PATCH request will look something like:
```
INSERT DATA {
  <https://tic-tac-moe.inrupt.net/public/games/tictactoe/1572260970777.ttl> 
    <http://data.totl.net/game/move> "4-2".
}
```

What is to stop a player from using a tuned version of the app that sends just any valid game state, rather than one that preserves the earlier moves from the game? Wouldn't it be better to invent a game state format that (like the Solid-Chess format) prevents such cheating at the data level?

**Comment by james-martin-jd** [comment]
It's true that the current game is not "perfect" by any means, and it currently serves as an example of many different things in the Solid world (sending / receiving global notifications, creating app containers and files, changing permissions, sending/receiving app-specific notifications, and more). 

The Tic Tac Toe game is based on a common React tutorial as well, as many developers who are new to the SDK are also new to React. The tutorial can be found here: https://reactjs.org/tutorial/tutorial.html, but it stores the data in a similar-but-slightly-different format. We wanted to keep the game close to this tutorial so people who had done the tutorial would feel more at home here.

I'm certainly open to ideas on how to improve it, but "cheating" wasn't a high priority for this particular feature.
