### ISSUE TITLE
Failed to build app 

### ISSUE THREAD

**Issue by AlessandroDellaTorre** [inrupt/generator-solid-react#300]
When i try to build the app(the application installed by default by the generator) i get this error: 
""" 
Failed to compile.
./node_modules/shacl-js/shacl.js
TypeError: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! solid-app@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the solid-app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/archyoda/.npm/_logs/2020-03-09T18_03_48_015Z-debug.log

"""
In the log: 
"""
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.2
3 info using node@v13.9.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle solid-app@0.1.0~prebuild: solid-app@0.1.0
6 info lifecycle solid-app@0.1.0~build: solid-app@0.1.0
7 verbose lifecycle solid-app@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle solid-app@0.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/archyoda/public_html/ProjectGrid/ReactApp/ReactGrid/node_modules/.bin
:/usr/local/bin:/usr/local/sbin:/usr/bin:/var/lib/flatpak/exports/bin:/opt/intel/mediasdk/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/rvm/bin
9 verbose lifecycle solid-app@0.1.0~build: CWD: /home/archyoda/public_html/ProjectGrid/ReactApp/ReactGrid
10 silly lifecycle solid-app@0.1.0~build: Args: [ '-c', 'node scripts/build.js' ]
11 silly lifecycle solid-app@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle solid-app@0.1.0~build: Failed to exec build script
13 verbose stack Error: solid-app@0.1.0 build: `node scripts/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid solid-app@0.1.0
15 verbose cwd /home/archyoda/public_html/ProjectGrid/ReactApp/ReactGrid
16 verbose Linux 5.4.11-arch1-1
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v13.9.0
19 verbose npm  v6.14.2
20 error code ELIFECYCLE
21 error errno 1
22 error solid-app@0.1.0 build: `node scripts/build.js`
22 error Exit status 1
23 error Failed at the solid-app@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

"""

![errorReact-Solid](https://user-images.githubusercontent.com/32387592/76244810-14379180-623b-11ea-9ec3-0a803843d730.png)

**Desktop:**
 - OS: OS: Arch Linux 
 - Npm version: 6.14.2 

did I do something wrong?
Thanks in advance

**Comment by james-martin-jd** [comment]
Interesting, we have removed shacl from the develop branch, but I don't think that change has been released yet. If you want, you can remove the shacl dependency from package.json and rerun `npm i`, then remove any shacl code. It should all be in the `FormModel/converter.component.js` and it is not used - there's a bunch of code in there we removed. If you'd like, you can compare that file to the version on the `develop` branch and copy the changes down to your generated app.

**Comment by AlessandroDellaTorre** [comment]
I have do what you tell to do and now all work properly. 
thank you!
